export {
  campaignLifecycleStatuses,
  parseCampaignCreateInput,
  parseCampaignCreateOutput,
  parseCampaignGetInput,
  parseCampaignGetOutput,
  parseCampaignListInput,
  parseCampaignListOutput,
  parseCampaignParticipantsAddFromDepartmentsInput,
  parseCampaignParticipantsAddFromDepartmentsOutput,
  parseCampaignParticipantsMutationInput,
  parseCampaignParticipantsMutationOutput,
  parseCampaignProgressGetInput,
  parseCampaignProgressGetOutput,
  parseCampaignSetModelVersionInput,
  parseCampaignSetModelVersionOutput,
  parseCampaignSnapshotListInput,
  parseCampaignSnapshotListOutput,
  parseCampaignTransitionInput,
  parseCampaignTransitionOutput,
  parseCampaignUpdateDraftInput,
  parseCampaignUpdateDraftOutput,
  parseCampaignWeightsSetInput,
  parseCampaignWeightsSetOutput,
} from "./v1/legacy";

export type {
  CampaignCreateInput,
  CampaignCreateOutput,
  CampaignGetInput,
  CampaignGetOutput,
  CampaignLifecycleStatus,
  CampaignListInput,
  CampaignListItem,
  CampaignListOutput,
  CampaignParticipantsAddFromDepartmentsInput,
  CampaignParticipantsAddFromDepartmentsOutput,
  CampaignParticipantsMutationInput,
  CampaignParticipantsMutationOutput,
  CampaignProgressGetInput,
  CampaignProgressGetOutput,
  CampaignProgressPendingGroupItem,
  CampaignProgressPendingItem,
  CampaignProgressStatusCounts,
  CampaignSetModelVersionInput,
  CampaignSetModelVersionOutput,
  CampaignSnapshotListInput,
  CampaignSnapshotListItem,
  CampaignSnapshotListOutput,
  CampaignTransitionInput,
  CampaignTransitionOutput,
  CampaignUpdateDraftInput,
  CampaignUpdateDraftOutput,
  CampaignWeightsSetInput,
  CampaignWeightsSetOutput,
} from "./v1/legacy";
